image: node:alpine

stages:
    - lint
    - build
    - deploy

variables:
    HUSKY: "0"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

before_script:
    - npm ci

lint:
    stage: lint
    script:
        - npm run format
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

build:
    stage: build
    script:
        - npm run build
    artifacts:
        paths:
            - dist/
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

deploy:
    stage: deploy
    script:
        - npm start
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
